package com.imagine.neatfeat.model.dal.entity;
// Generated Mar 21, 2019 12:44:38 AM by Hibernate Tools 4.3.1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.Entity;
import javax.persistence.*;
import java.util.Date;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="\"e-commerce\""
    , uniqueConstraints = @UniqueConstraint(columnNames="email")
)
public class Admin  implements com.imagine.neatfeat.model.dal.entity.Entity {


     private byte[] id;
     private String email;
     private String password;
     private String name;
     private Date birthdate;
     private boolean gender;
     private String address;
     private String phone;
     private String photoUrl;

    public Admin() {
    }

	
    public Admin(byte[] id, String email, String password, String name, Date birthdate, boolean gender) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.name = name;
        this.birthdate = birthdate;
        this.gender = gender;
    }
    public Admin(byte[] id, String email, String password, String name, Date birthdate, boolean gender, String address, String phone, String photoUrl) {
       this.id = id;
       this.email = email;
       this.password = password;
       this.name = name;
       this.birthdate = birthdate;
       this.gender = gender;
       this.address = address;
       this.phone = phone;
       this.photoUrl = photoUrl;
    }

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(columnDefinition = "BINARY(16)", name="id", unique=true, nullable=false)
    public byte[] getId() {
        return this.id;
    }
    
    public void setId(byte[] id) {
        this.id = id;
    }

    
    @Column(name="email", unique=true, nullable=false, length=40)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthdate", nullable=false, length=10)
    public Date getBirthdate() {
        return this.birthdate;
    }
    
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    
    @Column(name="gender", nullable=false)
    public boolean isGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }

    
    @Column(name="address", length=80)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="phone", length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="photo_url")
    public String getPhotoUrl() {
        return this.photoUrl;
    }
    
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }




}


