package com.imagine.neatfeat.model.dal.entity;
// Generated Mar 21, 2019 12:44:38 AM by Hibernate Tools 4.3.1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.Entity;
import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * DeliveryStatus generated by hbm2java
 */
@Entity
@Table(name="delivery_status"
    ,catalog="\"e-commerce\""
    , uniqueConstraints = @UniqueConstraint(columnNames="description") 
)
public class DeliveryStatus  implements com.imagine.neatfeat.model.dal.entity.Entity {


     private byte[] id;
     private String description;
     private Set<OrderProducts> orderProductses = new HashSet<OrderProducts>(0);

    public DeliveryStatus() {
    }

	
    public DeliveryStatus(byte[] id, String description) {
        this.id = id;
        this.description = description;
    }
    public DeliveryStatus(byte[] id, String description, Set<OrderProducts> orderProductses) {
       this.id = id;
       this.description = description;
       this.orderProductses = orderProductses;
    }

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(columnDefinition = "BINARY(16)", name="id", unique=true, nullable=false)
    public byte[] getId() {
        return this.id;
    }
    
    public void setId(byte[] id) {
        this.id = id;
    }

    
    @Column(name="description", unique=true, nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="deliveryStatus")
    public Set<OrderProducts> getOrderProductses() {
        return this.orderProductses;
    }
    
    public void setOrderProductses(Set<OrderProducts> orderProductses) {
        this.orderProductses = orderProductses;
    }




}


