package com.imagine.neatfeat.model.dal.entity;
// Generated Mar 21, 2019 12:44:38 AM by Hibernate Tools 4.3.1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.Entity;
import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * ShoppingCart generated by hbm2java
 */
@Entity
@Table(name="shopping_cart"
        ,catalog="\"e-commerce\""
        , uniqueConstraints = @UniqueConstraint(columnNames="user_id")
)
public class ShoppingCart  implements com.imagine.neatfeat.model.dal.entity.Entity {


    private UUID id;
    private User user;
    private Set<ShoppingCartProducts> shoppingCartProductses = new HashSet<ShoppingCartProducts>(0);

    private UUID uuid;

    public ShoppingCart() {
    }


    public ShoppingCart(UUID id, User user) {
        this.id = id;
        this.user = user;
    }
    public ShoppingCart(UUID id, User user, Set<ShoppingCartProducts> shoppingCartProductses) {
        this.id = id;
        this.user = user;
        this.shoppingCartProductses = shoppingCartProductses;
    }

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(columnDefinition = "BINARY(16)", name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", unique=true, nullable=false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="shoppingCart")
    public Set<ShoppingCartProducts> getShoppingCartProductses() {
        return this.shoppingCartProductses;
    }

    public void setShoppingCartProductses(Set<ShoppingCartProducts> shoppingCartProductses) {
        this.shoppingCartProductses = shoppingCartProductses;
    }
}


