package com.imagine.neatfeat.model.dal.entity;
// Generated Mar 21, 2019 12:44:38 AM by Hibernate Tools 4.3.1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.Entity;
import javax.persistence.*;
import java.util.UUID;

/**
 * UserVisitProducts generated by hbm2java
 */
@Entity
@Table(name="user_visit_products"
        ,catalog="\"ecommerce\""
        , uniqueConstraints = @UniqueConstraint(columnNames={"user_id", "product_id"})
)
public class UserVisitProducts  implements com.imagine.neatfeat.model.dal.entity.Entity {


    private UUID id;
    private Product product;
    private Userrr userrr;
    private int visitCount;

    private UUID uuid;

    public UserVisitProducts() {
    }

    public UserVisitProducts(UUID id, Product product, Userrr userrr, int visitCount) {
        this.id = id;
        this.product = product;
        this.userrr = userrr;
        this.visitCount = visitCount;
    }

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(columnDefinition = "BINARY(16)", name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public Userrr getUserrr() {
        return this.userrr;
    }

    public void setUserrr(Userrr userrr) {
        this.userrr = userrr;
    }


    @Column(name="visit_count", nullable=false)
    public int getVisitCount() {
        return this.visitCount;
    }

    public void setVisitCount(int visitCount) {
        this.visitCount = visitCount;
    }


}


