package com.imagine.neatfeat.model.dal.entity;
// Generated Mar 21, 2019 12:44:38 AM by Hibernate Tools 4.3.1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.Entity;
import javax.persistence.*;
import java.util.UUID;

/**
 * WishingListProducts generated by hbm2java
 */
@Entity
@Table(name="wishing_list_products"
        ,catalog="\"e-commerce\""
        , uniqueConstraints = @UniqueConstraint(columnNames={"wishing_list_id", "product_id"})
)
public class WishingListProducts  implements com.imagine.neatfeat.model.dal.entity.Entity {


    private UUID id;
    private Product product;
    private WishingList wishingList;
    private int priceBeforeDiscount;
    private Short discount;



    private UUID uuid;

    public WishingListProducts() {
    }


    public WishingListProducts(UUID id, Product product, WishingList wishingList, int priceBeforeDiscount) {
        this.id = id;
        this.product = product;
        this.wishingList = wishingList;
        this.priceBeforeDiscount = priceBeforeDiscount;
    }
    public WishingListProducts(UUID id, Product product, WishingList wishingList, int priceBeforeDiscount, Short discount) {
        this.id = id;
        this.product = product;
        this.wishingList = wishingList;
        this.priceBeforeDiscount = priceBeforeDiscount;
        this.discount = discount;
    }

    @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "uuid2")
    @Column(columnDefinition = "BINARY(16)", name="id", unique=true, nullable=false)
    public UUID getId() {
        return this.id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false)
    public Product getProduct() {
        return this.product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wishing_list_id", nullable=false)
    public WishingList getWishingList() {
        return this.wishingList;
    }

    public void setWishingList(WishingList wishingList) {
        this.wishingList = wishingList;
    }


    @Column(name="price_before_discount", nullable=false)
    public int getPriceBeforeDiscount() {
        return this.priceBeforeDiscount;
    }

    public void setPriceBeforeDiscount(int priceBeforeDiscount) {
        this.priceBeforeDiscount = priceBeforeDiscount;
    }


    @Column(name="discount")
    public Short getDiscount() {
        return this.discount;
    }

    public void setDiscount(Short discount) {
        this.discount = discount;
    }


}


